name: Deploy to AWS S3

env:
  AWS_REGION: "eu-north-1"
  BUCKET_NAME: "ofek-github-actions-bucket"
  PACKAGE_NAME: "TEST-APP-${{ github.sha }}.zip"

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  deployAWS:
    runs-on: ubuntu-latest
    steps:
      - name: get code
        uses: actions/checkout@v4

      - name: Check folder 
        run: |
          ls -la
          aws --version
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Create package
        run: zip -r ${{ env.PACKAGE_NAME }} ./ -x *.git*
          
      - name: Send package
        run: aws s3 cp ${{ env.PACKAGE_NAME }} s3://${{ env.BUCKET_NAME }}/
        
      - uses: actions/checkout@v4

      - run: ls -la